language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: 1.0
notifications:
    email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
    - $TESTCMD -e 'using Pkg; Pkg.clone(pwd());
          Pkg.build("TestGtk");
          Pkg.test("TestGtk"; coverage=true)'