language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0

notifications:
    email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-dev
